/**
 * IATA airport-code lookup for shipment labels. Keyed by normalized
 * (lowercase + trimmed) city name. Curated for xpmile operator routes —
 * GCC + MENA heavy, with South Asia, Southeast / East Asia, key Europe
 * / North America / Africa hubs. Extend as new lanes are added.
 *
 * Multi-airport cities (London, New York, Paris, Tokyo, …) use the
 * primary international airport. A shipment that genuinely needs LGW
 * instead of LHR is rare enough to live as a manual override on the
 * printed label rather than a per-shipment field today.
 *
 * Aliases (Bombay → BOM, Calcutta → CCU, São Paulo / Sao Paulo, etc.)
 * are duplicated as their own keys so operator-typed legacy strings
 * still resolve. Keep alias keys near their canonical sibling for
 * easy maintenance.
 */
export const IATA_BY_CITY: Record<string, string> = {
  // ── GCC ──────────────────────────────────────────────────────────
  'dubai':              'DXB',
  'abu dhabi':          'AUH',
  'sharjah':            'SHJ',
  'al ain':             'AAN',
  'ras al khaimah':     'RKT',
  'doha':               'DOH',
  'kuwait city':        'KWI',
  'kuwait':             'KWI',
  'manama':             'BAH',
  'muscat':             'MCT',
  'salalah':            'SLL',

  // ── Saudi Arabia ─────────────────────────────────────────────────
  'riyadh':   'RUH',
  'jeddah':   'JED',
  'dammam':   'DMM',
  'medina':   'MED',
  'madinah':  'MED',
  'taif':     'TIF',
  'tabuk':    'TUU',
  'abha':     'AHB',

  // ── Levant / MENA ────────────────────────────────────────────────
  'cairo':       'CAI',
  'alexandria':  'HBE',
  'amman':       'AMM',
  'beirut':      'BEY',
  'damascus':    'DAM',
  'aleppo':      'ALP',
  'baghdad':     'BGW',
  'basra':       'BSR',
  'erbil':       'EBL',
  'tehran':      'IKA',
  'mashhad':     'MHD',
  'istanbul':    'IST',
  'ankara':      'ESB',
  'izmir':       'ADB',
  'casablanca':  'CMN',
  'rabat':       'RBA',
  'marrakech':   'RAK',
  'algiers':     'ALG',
  'tunis':       'TUN',
  'tripoli':     'TIP',
  'khartoum':    'KRT',
  'sanaa':       'SAH',
  'tel aviv':    'TLV',

  // ── South Asia: India ────────────────────────────────────────────
  'mumbai':             'BOM',
  'bombay':             'BOM',
  'delhi':              'DEL',
  'new delhi':          'DEL',
  'bangalore':          'BLR',
  'bengaluru':          'BLR',
  'chennai':            'MAA',
  'madras':             'MAA',
  'hyderabad':          'HYD',
  'kolkata':            'CCU',
  'calcutta':           'CCU',
  'ahmedabad':          'AMD',
  'pune':               'PNQ',
  'kochi':              'COK',
  'cochin':             'COK',
  'trivandrum':         'TRV',
  'thiruvananthapuram': 'TRV',
  'kozhikode':          'CCJ',
  'calicut':            'CCJ',
  'mangalore':          'IXE',
  'lucknow':            'LKO',
  'jaipur':             'JAI',
  'goa':                'GOI',
  'chandigarh':         'IXC',
  'amritsar':           'ATQ',
  'patna':              'PAT',
  'guwahati':           'GAU',
  'srinagar':           'SXR',
  'visakhapatnam':      'VTZ',
  'coimbatore':         'CJB',
  'indore':             'IDR',
  'bhubaneswar':        'BBI',
  'nagpur':             'NAG',
  'vijayawada':         'VGA',
  'tiruchirappalli':    'TRZ',
  'trichy':             'TRZ',
  'madurai':            'IXM',
  'varanasi':           'VNS',
  'ranchi':             'IXR',

  // ── Pakistan ─────────────────────────────────────────────────────
  'karachi':     'KHI',
  'lahore':      'LHE',
  'islamabad':   'ISB',
  'peshawar':    'PEW',
  'multan':      'MUX',
  'faisalabad':  'LYP',
  'sialkot':     'SKT',
  'quetta':      'UET',

  // ── Other South Asia ─────────────────────────────────────────────
  'dhaka':       'DAC',
  'chittagong':  'CGP',
  'colombo':     'CMB',
  'kathmandu':   'KTM',
  'male':        'MLE',

  // ── Southeast Asia ───────────────────────────────────────────────
  'singapore':         'SIN',
  'kuala lumpur':      'KUL',
  'penang':            'PEN',
  'bangkok':           'BKK',
  'phuket':            'HKT',
  'chiang mai':        'CNX',
  'jakarta':           'CGK',
  'denpasar':          'DPS',
  'bali':              'DPS',
  'surabaya':          'SUB',
  'manila':            'MNL',
  'cebu':              'CEB',
  'davao':             'DVO',
  'ho chi minh city':  'SGN',
  'ho chi minh':       'SGN',
  'saigon':            'SGN',
  'hanoi':             'HAN',
  'phnom penh':        'PNH',
  'yangon':            'RGN',
  'vientiane':         'VTE',

  // ── East Asia ────────────────────────────────────────────────────
  'tokyo':       'HND',
  'osaka':       'KIX',
  'nagoya':      'NGO',
  'sapporo':     'CTS',
  'fukuoka':     'FUK',
  'seoul':       'ICN',
  'busan':       'PUS',
  'beijing':     'PEK',
  'shanghai':    'PVG',
  'guangzhou':   'CAN',
  'shenzhen':    'SZX',
  'chengdu':     'CTU',
  'chongqing':   'CKG',
  'xian':        'XIY',
  'kunming':     "KMG",
  'hong kong':   'HKG',
  'macau':       'MFM',
  'taipei':      'TPE',
  'kaohsiung':   'KHH',
  'ulan bator':  'UBN',
  'ulaanbaatar': 'UBN',

  // ── Europe (West / North) ────────────────────────────────────────
  'london':      'LHR',
  'manchester':  'MAN',
  'birmingham':  'BHX',
  'edinburgh':   'EDI',
  'glasgow':     'GLA',
  'dublin':      'DUB',
  'paris':       'CDG',
  'nice':        'NCE',
  'marseille':   'MRS',
  'lyon':        'LYS',
  'toulouse':    'TLS',
  'amsterdam':   'AMS',
  'brussels':    'BRU',
  'luxembourg':  'LUX',
  'frankfurt':   'FRA',
  'munich':      'MUC',
  'berlin':      'BER',
  'hamburg':     'HAM',
  'düsseldorf':  'DUS',
  'dusseldorf':  'DUS',
  'cologne':     'CGN',
  'stuttgart':   'STR',
  'zurich':      'ZRH',
  'geneva':      'GVA',
  'vienna':      'VIE',
  'rome':        'FCO',
  'milan':       'MXP',
  'venice':      'VCE',
  'naples':      'NAP',
  'madrid':      'MAD',
  'barcelona':   'BCN',
  'valencia':    'VLC',
  'lisbon':      'LIS',
  'porto':       'OPO',
  'athens':      'ATH',
  'stockholm':   'ARN',
  'copenhagen':  'CPH',
  'oslo':        'OSL',
  'helsinki':    'HEL',
  'warsaw':      'WAW',
  'prague':      'PRG',
  'budapest':    'BUD',
  'bucharest':   'OTP',
  'sofia':       'SOF',

  // ── North America ────────────────────────────────────────────────
  'new york':       'JFK',
  'newark':         'EWR',
  'los angeles':    'LAX',
  'san francisco':  'SFO',
  'chicago':        'ORD',
  'miami':          'MIA',
  'dallas':         'DFW',
  'houston':        'IAH',
  'atlanta':        'ATL',
  'boston':         'BOS',
  'washington':     'IAD',
  'seattle':        'SEA',
  'philadelphia':   'PHL',
  'detroit':        'DTW',
  'phoenix':        'PHX',
  'las vegas':      'LAS',
  'orlando':        'MCO',
  'denver':         'DEN',
  'minneapolis':    'MSP',
  'san diego':      'SAN',
  'austin':         'AUS',
  'toronto':        'YYZ',
  'vancouver':      'YVR',
  'montreal':       'YUL',
  'calgary':        'YYC',
  'ottawa':         'YOW',
  'edmonton':       'YEG',
  'mexico city':    'MEX',
  'cancun':         'CUN',
  'guadalajara':    'GDL',

  // ── Africa ───────────────────────────────────────────────────────
  'johannesburg':   'JNB',
  'cape town':      'CPT',
  'durban':         'DUR',
  'nairobi':        'NBO',
  'mombasa':        'MBA',
  'addis ababa':    'ADD',
  'lagos':          'LOS',
  'abuja':          'ABV',
  'accra':          'ACC',
  'dar es salaam':  'DAR',
  'kampala':        'EBB',
  'kigali':         'KGL',
  'luanda':         'LAD',
  'kinshasa':       'FIH',
  'dakar':          'DSS',
  'abidjan':        'ABJ',
  'harare':         'HRE',
  'maputo':         'MPM',

  // ── Oceania ──────────────────────────────────────────────────────
  'sydney':         'SYD',
  'melbourne':      'MEL',
  'brisbane':       'BNE',
  'perth':          'PER',
  'adelaide':       'ADL',
  'auckland':       'AKL',
  'wellington':     'WLG',
  'christchurch':   'CHC',

  // ── Russia / Central Asia / Caucasus ─────────────────────────────
  'moscow':           'SVO',
  'saint petersburg': 'LED',
  'st petersburg':    'LED',
  'baku':             'GYD',
  'almaty':           'ALA',
  'astana':           'NQZ',
  'nur-sultan':       'NQZ',
  'tashkent':         'TAS',
  'tbilisi':          'TBS',
  'yerevan':          'EVN',

  // ── Latin America ────────────────────────────────────────────────
  'sao paulo':      'GRU',
  'são paulo':      'GRU',
  'rio de janeiro': 'GIG',
  'brasilia':       'BSB',
  'brasília':       'BSB',
  'buenos aires':   'EZE',
  'lima':           'LIM',
  'bogota':         'BOG',
  'bogotá':         'BOG',
  'santiago':       'SCL',
  'caracas':        'CCS',
  'quito':          'UIO',
  'panama city':    'PTY'
};

/**
 * Look up the IATA code for a city. Case-insensitive + whitespace-trimmed
 * match against the curated table above. Returns `undefined` on miss —
 * callers should provide their own fallback (LabelService uses the first
 * three characters of the city, upper-cased).
 */
export function lookupIata(city: string | undefined): string | undefined {
  if (!city) return undefined;
  const key = city.toLowerCase().trim();
  return IATA_BY_CITY[key];
}
