// modules/module/wsdbagent/test/sign_jwt_dispatch_test.cc
//
// Tests for the on-prem side of the SIGN_JWT op (Phase A part 2).
// Verifies sign_jwt_on_prem():
//   - reads idp.idp_signing_keys correctly
//   - produces an RS256 signature that verifies under the matching
//     public key (full round-trip with a build-time RSA-2048 fixture)
//   - resolves "current" → the active key (active:true)
//   - returns ok=false with a clear errmsg on missing/malformed inputs
//
// The RSA test keypair lives in CMAKE_BINARY_DIR/idp_test_keys/ and is
// generated by test/CMakeLists.txt's add_custom_command. The paths are
// passed in via the IDP_TEST_PRIV_KEY_PATH / IDP_TEST_PUB_KEY_PATH
// preprocessor macros.

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>

#include "dbproto.hpp"
#include "json.hpp"
#include "mongodbc.hpp"
#include "sign_jwt_on_prem.hpp"

namespace {

// ── MockMongodbClient ────────────────────────────────────────────────────────
// Minimal IMongodbClient impl: only get_document is wired; the rest throw
// or return defaults. SIGN_JWT only calls get_document.

class MockMongodbClient : public IMongodbClient {
public:
  std::string canned_doc;     // returned by get_document
  std::string last_coll;
  std::string last_query;
  std::string last_projection;
  std::string database;

  const std::string &get_database() const override { return database; }

  std::string get_document(const std::string &coll,
                           const std::string &query,
                           const std::string &projection) override {
    last_coll       = coll;
    last_query      = query;
    last_projection = projection;
    return canned_doc;
  }

  // Stubs — never called by sign_jwt_on_prem.
  std::string create_document(const std::string &, const std::string &,
                              const std::string &) override { return {}; }
  std::int32_t create_bulk_document(const std::string &, const std::string &,
                                    const std::string &) override { return 0; }
  bool update_collection(const std::string &, const std::string &,
                         const std::string &) override { return false; }
  std::int32_t update_bulk_document(const std::string &,
                                    const std::vector<std::string> &,
                                    const std::vector<std::string> &) override { return 0; }
  bool delete_document(const std::string &, const std::string &) override { return false; }
  std::string get_documents(const std::string &, const std::string &,
                            const std::string &) override { return {}; }
  std::string get_documents(const std::string &, const std::string &) override { return {}; }
  std::string next_awbno(const std::string & = "AWB") override { return {}; }
  std::string store_file(const std::string &, const std::string &,
                         const std::vector<std::uint8_t> &) override { return {}; }
  std::vector<std::uint8_t> fetch_file(const std::string &) override { return {}; }
  std::vector<std::uint8_t> fetch_file_by_id(const std::string &) override { return {}; }
  bool delete_file(const std::string &) override { return false; }
};

// ── helpers ──────────────────────────────────────────────────────────────────

std::string read_file(const char *path) {
  std::ifstream f(path);
  if (!f) {
    ADD_FAILURE() << "could not read fixture: " << path;
    return {};
  }
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

dbproto::DbRequest make_sign_request(const std::string &kid_hint,
                                      const std::string &to_sign,
                                      std::int32_t reqid = 1) {
  dbproto::DbRequest req;
  req.reqid = reqid;
  req.op    = DbOp::SIGN_JWT;
  req.db    = "idp";
  req.coll  = "idp_signing_keys";
  req.sval  = kid_hint;
  req.doc.assign(to_sign.begin(), to_sign.end());
  return req;
}

// Verify an RS256 signature against a public key PEM. Mirrors the
// signing primitive — used by tests only.
bool rs256_verify(const std::string &pub_pem,
                  const std::vector<std::uint8_t> &to_sign,
                  const std::vector<std::uint8_t> &signature) {
  std::unique_ptr<BIO, decltype(&BIO_free_all)> bio{
      BIO_new_mem_buf(pub_pem.data(), static_cast<int>(pub_pem.size())),
      BIO_free_all};
  if (!bio) return false;
  std::unique_ptr<EVP_PKEY, decltype(&EVP_PKEY_free)> pkey{
      PEM_read_bio_PUBKEY(bio.get(), nullptr, nullptr, nullptr),
      EVP_PKEY_free};
  if (!pkey) return false;

  std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)> ctx{
      EVP_MD_CTX_new(), EVP_MD_CTX_free};
  if (!ctx) return false;

  if (1 != EVP_DigestVerifyInit(ctx.get(), nullptr, EVP_sha256(),
                                 nullptr, pkey.get())) {
    return false;
  }
  if (1 != EVP_DigestVerifyUpdate(ctx.get(),
                                   to_sign.data(), to_sign.size())) {
    return false;
  }
  return 1 == EVP_DigestVerifyFinal(ctx.get(),
                                     signature.data(), signature.size());
}

} // namespace

// ── Tests ────────────────────────────────────────────────────────────────────

TEST(SignJwtDispatch, RoundTrip_SignThenVerifyWithPublicKey) {
  const std::string priv_pem = read_file(IDP_TEST_PRIV_KEY_PATH);
  const std::string pub_pem  = read_file(IDP_TEST_PUB_KEY_PATH);
  ASSERT_FALSE(priv_pem.empty()) << "missing private key fixture";
  ASSERT_FALSE(pub_pem.empty())  << "missing public key fixture";

  MockMongodbClient db;
  nlohmann::json key_doc = {
      // Production shape (matches Vaadin IdpSigningKeyService): the
      // domain kid lives in its own `kid` field, NOT in _id (which is
      // an auto-gen ObjectId in production). Earlier tests seeded
      // `_id = "kid-…"` which agreed with the old buggy reader; the
      // new reader (paired with PR #33's idp_jwks fix) reads `kid`.
      {"kid",           "kid-test-1"},
      {"alg",           "RS256"},
      {"privateKeyPem", priv_pem},
      {"active",        true},
  };
  db.canned_doc = key_doc.dump();

  const std::string to_sign = "header_b64u.payload_b64u";
  auto req = make_sign_request("kid-test-1", to_sign);
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;

  agent::sign_jwt_on_prem(db, req, rsp);

  ASSERT_TRUE(rsp.ok) << "sign failed: " << rsp.errmsg;
  EXPECT_EQ(rsp.sval, "kid-test-1");
  EXPECT_FALSE(rsp.data.empty()) << "signature is empty";

  const std::vector<std::uint8_t> to_sign_bytes(to_sign.begin(), to_sign.end());
  EXPECT_TRUE(rs256_verify(pub_pem, to_sign_bytes, rsp.data))
      << "signature did not verify under the matching public key";

  // Sanity: tampering with one signed byte invalidates the signature.
  auto tampered = to_sign_bytes;
  tampered.front() ^= 0x01;
  EXPECT_FALSE(rs256_verify(pub_pem, tampered, rsp.data))
      << "tampered payload should not verify";
}

TEST(SignJwtDispatch, KidCurrent_QueriesByActiveTrue) {
  const std::string priv_pem = read_file(IDP_TEST_PRIV_KEY_PATH);
  MockMongodbClient db;
  nlohmann::json key_doc = {
      {"kid", "active-kid"}, {"alg", "RS256"},
      {"privateKeyPem", priv_pem}, {"active", true},
  };
  db.canned_doc = key_doc.dump();

  auto req = make_sign_request("current", "h.p");
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;
  agent::sign_jwt_on_prem(db, req, rsp);

  ASSERT_TRUE(rsp.ok) << rsp.errmsg;
  EXPECT_EQ(rsp.sval, "active-kid");
  // The query targeted the active key, not a specific kid.
  EXPECT_NE(db.last_query.find("\"active\""), std::string::npos)
      << "expected query against active:true; got: " << db.last_query;
}

TEST(SignJwtDispatch, SpecificKid_QueriesById) {
  const std::string priv_pem = read_file(IDP_TEST_PRIV_KEY_PATH);
  MockMongodbClient db;
  nlohmann::json key_doc = {
      {"kid", "kid-specific"}, {"alg", "RS256"},
      {"privateKeyPem", priv_pem}, {"active", false},
  };
  db.canned_doc = key_doc.dump();

  auto req = make_sign_request("kid-specific", "h.p");
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;
  agent::sign_jwt_on_prem(db, req, rsp);

  ASSERT_TRUE(rsp.ok) << rsp.errmsg;
  EXPECT_EQ(rsp.sval, "kid-specific");
  EXPECT_NE(db.last_query.find("kid-specific"), std::string::npos)
      << "expected query by _id=kid-specific; got: " << db.last_query;
}

TEST(SignJwtDispatch, UnknownKid_Errors) {
  MockMongodbClient db;
  db.canned_doc = "";  // get_document returns empty when no doc

  auto req = make_sign_request("nonexistent-kid", "h.p");
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;
  agent::sign_jwt_on_prem(db, req, rsp);

  EXPECT_FALSE(rsp.ok);
  EXPECT_NE(rsp.errmsg.find("nonexistent-kid"), std::string::npos);
  EXPECT_TRUE(rsp.data.empty());
}

TEST(SignJwtDispatch, NonRs256AlgInStoredKey_Errors) {
  const std::string priv_pem = read_file(IDP_TEST_PRIV_KEY_PATH);
  MockMongodbClient db;
  nlohmann::json key_doc = {
      {"kid", "k"}, {"alg", "ES256"},  // wrong alg
      {"privateKeyPem", priv_pem}, {"active", true},
  };
  db.canned_doc = key_doc.dump();

  auto req = make_sign_request("current", "h.p");
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;
  agent::sign_jwt_on_prem(db, req, rsp);

  EXPECT_FALSE(rsp.ok);
  EXPECT_NE(rsp.errmsg.find("ES256"), std::string::npos);
}

TEST(SignJwtDispatch, MalformedPrivateKey_Errors) {
  MockMongodbClient db;
  nlohmann::json key_doc = {
      {"kid", "k"}, {"alg", "RS256"},
      {"privateKeyPem", "-----BEGIN PRIVATE KEY-----\nGARBAGE\n-----END PRIVATE KEY-----\n"},
      {"active", true},
  };
  db.canned_doc = key_doc.dump();

  auto req = make_sign_request("current", "h.p");
  dbproto::DbResponse rsp;
  rsp.reqid = req.reqid;
  agent::sign_jwt_on_prem(db, req, rsp);

  EXPECT_FALSE(rsp.ok);
  EXPECT_NE(rsp.errmsg.find("parse"), std::string::npos);
}
